// All types are derived from Zod schemas in schemas.ts
// This file re-exports them for backward compatibility

export type {
  PunchlistConfig,
  IssueTrackerConfig,
  StorageConfig,
  AuthConfig,
  WidgetConfig,
  TestCase,
  TestRound,
  TestResult,
  Tester,
  IssueTrackerType,
  StorageAdapterType,
  AuthAdapterType,
  AIToolChoice,
  Category,
  TestCasePriority,
  Round,
  Result,
  User,
  RoundStatus,
  ResultSeverity,
  UserRole,
  CreateRoundInput,
  UpdateRoundInput,
  SubmitResultInput,
  CreateUserInput,
} from './schemas.js';
